apiVersion: apps/v1
kind: Deployment
metadata:
  name: world-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: world-service
  template:
    metadata:
      labels:
        app: world-service
    spec:
      containers:
        - name: world-service
          image: debugimages.azurecr.io/world-service:latest
          ports:
            - containerPort: 8080
          env:                        # Add this section for environment variables
            - name: ASPNETCORE_ENVIRONMENT
              value: Development      # Set the value to "Development"
---
apiVersion: v1
kind: Service
metadata:
  name: world-service
spec:
  selector:
    app: world-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
